stages:
  - preparation
  - depedencies
  - test
  - build

before_script:
  - ls

# start preparation
check_packages:
  stage: preparation
  image: addeanz/ionic_capacitor
  script:
    - node --version
    - ionic --version
    - ionic capacitor --version

# end preparation

# start depedencies
install_dependencies:
  stage: depedencies
  image: addeanz/ionic_capacitor
  script:
    - npm install

ionic_doctor:
  stage: depedencies
  image: addeanz/ionic_capacitor
  script:
    - ionic doctor check
# end depedencies

# start test
code_analysis:
  stage: test
  image: addeanz/ionic_capacitor
  script:
    - npm install
    - npm run lint

# code_e2e:
#   stage: test
#   image: addeanz/ionic_capacitor
#   script:
#     - npm install
#     - npm run e2e

# code_test:
#   stage: test
#   image: addeanz/ionic_capacitor
#   script:
#     - npm install
#     - npm run test
# end test

# start build
build_android:
  stage: build
  image: addeanz/ionic_capacitor
  script:
    - npm install
    - npm run build
    - npx cap add android
    - npx cap sync
  allow_failure: true

build_ios:
  stage: build
  image: addeanz/ionic_capacitor
  script:
    - npm install
    - npm run build
    - npx cap add ios
    - npx cap sync
  allow_failure: true
# end build

